# 2022/12/24/FRI

In [3]:
import numpy as np

In [9]:
np.linspace(0,4,5)
# 0부터 4까지 다섯개로 쪼갠다

array([0., 1., 2., 3., 4.])

In [11]:
np.arange(10)
# 0부터 10개의 숫자

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a=np.array([10,20,3])

In [13]:
a.shape 
# 1차원 행렬에 방 세개

(3,)

In [15]:
a.ndim
# 1차원

1

In [16]:
a.dtype # array에 들어간 숫자들이 어떤 형식으로?

dtype('int32')

In [17]:
a.size # 몇개 들어가 있니

3

In [18]:
type(a) #몇차원이고 될 수 있음, nd=ndimension

numpy.ndarray

- np.array도 sequence 타입 => index,slicing가능

In [19]:
a[2]

3

In [20]:
a[2]=30.8

In [21]:
a

array([10, 20, 30])

> `소수점 날라가고 30으로 저장됨` 

In [22]:
a.dtype

dtype('int32')

In [23]:
a=a.astype('float64')

In [24]:
a[2]=30.865

In [25]:
a

array([10.   , 20.   , 30.865])

In [26]:
a.dtype

dtype('float64')

- `소수점도 가능한 자료형으로 변경해줬음`

In [27]:
b=np.array([10.,20.,30.])

In [31]:
b.dtype

dtype('float64')

- `애초에 이렇게 dot을 지정해주고 들어가면 float으로 활용가능`

In [32]:
c=np.array([10.2,20.3,50.58],'int32')

In [33]:
c

array([10, 20, 50])

- 이렇게 'int32'로 지정해줄 수 있음

In [34]:
x=np.array([7,9,11])
y=x/2

In [35]:
y

array([3.5, 4.5, 5.5])

In [36]:
x.dtype

dtype('int32')

In [37]:
y.dtype

dtype('float64')

- x가 정수로 시작했어도 y는 divide를 사용하고 있기에 알아서 np에서 float64로 지정함

##### `int32` $vs$ `int64`

In [38]:
x=np.array([0])

In [39]:
x[0]=2147483647

In [40]:
x

array([2147483647])

In [41]:
x[0]=x[0]+1

C:\Users\ehfus\AppData\Local\Temp/ipykernel_11580/4237261130.py:1: RuntimeWarning: overflow encountered in long_scalars
  x[0]=x[0]+1


- 2147483647은 int32에서 수용할 수 있는 최대의 숫자임, 따라서 여기서 1만 더해주더라도 수용하지 못하게 됨

In [42]:
x=np.array([0],'int64')

In [43]:
x[0]=2147483647

In [44]:
x[0]+1

2147483648

- dtype을 int64로 바꿨기 때문에 int32에서 최대였던 것보다 더 수용할 수 있게 됨

In [45]:
a=np.array([10,'abc',20]) # 꼭 list형태로 줘야 함    

In [46]:
a.dtype #섞여있음

dtype('<U11')

In [48]:
# a*2

- 섞여있으면 이런 연산은 불가

In [49]:
a=np.array([[10,20,30],[40,50,60]])

In [50]:
a # 2차원

array([[10, 20, 30],
       [40, 50, 60]])

In [51]:
a.shape # 2x3행렬로 해석해도 될듯

(2, 3)

In [53]:
a.size

6

In [54]:
a=np.array([[10,20,30],[40,50,60],[5,6,8]])

In [55]:
a

array([[10, 20, 30],
       [40, 50, 60],
       [ 5,  6,  8]])

In [56]:
a.size

9

In [57]:
a=np.array([[10,20,30],
            [40,50,60],
           [55,54,88]
            ,[112,123,41]])

In [58]:
a

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 55,  54,  88],
       [112, 123,  41]])

In [59]:
a.ndim

2

In [60]:
a.shape

(4, 3)

In [61]:
a=np.array([10+10j,10+60j])

In [62]:
a

array([10.+10.j, 10.+60.j])

In [63]:
a=np.array([10,20],'complex')

In [64]:
a

array([10.+0.j, 20.+0.j])

---

In [65]:
a=np.array([10,20])

In [66]:
b=np.matrix([10,20])

In [67]:
a.ndim

1

In [68]:
b.ndim

2

In [69]:
# b=np.matrix([[[10]]])
# error = > matrix는 2차원만 가능

In [70]:
a=np.array([10,20,30])

In [71]:
a=np.insert(a,2,5)
# a라는 np.array의 2번째 인덱스에 5를 넣어라

In [72]:
a

array([10, 20,  5, 30])

In [75]:
a=np.delete(a,2)

In [76]:
a # 두번째 인덱스 삭제

array([10, 20, 30])

In [77]:
a=np.array([1,2,3])

In [89]:
a=np.arange(3)

In [90]:
a # 0부터 시작해서 숫자 3개를 채워줌

array([0, 1, 2])

In [91]:
a=np.zeros(2)

In [92]:
a

array([0., 0.])

In [93]:
a=np.zeros((2,3))

In [94]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [95]:
a=np.ones((2,3))

In [96]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [99]:
a=np.logspace(0,5,4) # log scale로!

In [101]:
a

array([1.00000000e+00, 4.64158883e+01, 2.15443469e+03, 1.00000000e+05])

---

In [102]:
a=np.array([10,20,30])
b=np.array([1,2,3])

In [103]:
a+b

array([11, 22, 33])

In [104]:
a-b

array([ 9, 18, 27])

In [105]:
b-a

array([ -9, -18, -27])

In [106]:
a*b

array([10, 40, 90])

In [107]:
a/b

array([10., 10., 10.])

In [108]:
c=a**2

In [109]:
c

array([100, 400, 900], dtype=int32)

In [110]:
idx=a<20

In [111]:
idx

array([ True, False, False])

In [112]:
a=a+1

In [113]:
a

array([11, 21, 31])

In [114]:
a+=1

In [115]:
a

array([12, 22, 32])

In [116]:
a*=2

In [117]:
a

array([24, 44, 64])

In [118]:
a=a*2

In [119]:
a

array([ 48,  88, 128])

In [125]:
a=np.array([10,50,9]) # int
b=np.array([50.,5.,8.]) #float

In [126]:
a=a+b

In [127]:
a

array([60., 55., 17.])

In [129]:
# a+=b
# a에b를 더해서 a를 업데이트 하는 건 자료형이 달라서 안 된다고 함
# 되게 하려면 자료형을 맞춰주면 됨

In [130]:
c=a+b # 이건 됨

In [131]:
c

array([110.,  60.,  25.])

----

In [132]:
a=np.array([10,50,9]) 
b=np.array([50,5,8]) 

In [133]:
np.add(a,b)

array([60, 55, 17])

In [134]:
np.subtract(a,b)

array([-40,  45,   1])

In [135]:
np.divide(a,b)

array([ 0.2  , 10.   ,  1.125])

In [136]:
np.multiply(a,b)

array([500, 250,  72])

In [139]:
np.divmod(a,b) # 몫과 나머지 

(array([[0, 2, 0],
        [0, 0, 0]], dtype=int32),
 array([[ 0,  0,  1],
        [10,  0,  1]], dtype=int32))

In [140]:
np.exp(b)

array([5.18470553e+21, 1.48413159e+02, 2.98095799e+03])

In [141]:
np.sqrt(a)

array([[0.        , 3.16227766, 1.        ],
       [3.16227766, 0.        , 1.        ]])

----

In [142]:
a=np.array([10,20,3])

In [150]:
np.mean(a)

11.0

In [151]:
a.mean()

11.0

In [152]:
# 가중치 줘서 평균 구할 때 사용
np.average(a)

11.0

In [153]:
# 머신러닝 학습시 가중치 주는 법
np.average(a,weights=[1,1,1])

11.0

In [154]:
np.average(a,weights=[1,1,0])

15.0

In [155]:
np.average(a,weights=[0,1,1])

11.5

In [156]:
np.median(a)

10.0

In [157]:
np.cumsum(a)
# 앞에 있는 숫자들을 더해주는 것

array([10, 30, 33], dtype=int32)

In [159]:
# 공분산
np.cov(a)

array(73.)

In [160]:
# 표준편차
np.std(a)

6.97614984548545

In [162]:
# 분산
np.var(a)

48.666666666666664

In [163]:
x=np.array([10,20,30])

In [164]:
x.sum()

60

In [165]:
x=np.array([10.,40.,20.,5.,15.])

In [166]:
x.min()

5.0

In [167]:
x.max()

40.0

In [168]:
x.argmin() 
# index 0에 최솟값이 존재함

3

In [169]:
# 최솟값과 최솟값의 자릿값을 한 번에 알아보기a
x_min,x_min_idx=x.min(),x.argmin()

In [170]:
# ptp= peak-to-peak
# 최솟값과 최댓값의 차이
x.ptp()

35.0

In [171]:
y=np.sort(x)

In [172]:
y

array([ 5., 10., 15., 20., 40.])

In [173]:
idx = np.argsort(x)

In [174]:
idx

array([3, 0, 4, 2, 1], dtype=int64)

In [175]:
y

array([ 5., 10., 15., 20., 40.])

- sort된 값들이 원래 어디에 위치해 있었는지

In [176]:
x[idx]

array([ 5., 10., 15., 20., 40.])

In [177]:
y=x[idx]

In [178]:
y

array([ 5., 10., 15., 20., 40.])

In [179]:
a=np.array([20,10,30])
b=np.array([-5,25])

In [180]:
# b를 a에 넣을 때 어느 자리에 넣어야 sorting이 유지가 되는지?
np.searchsorted(a,b)

array([0, 2], dtype=int64)

In [181]:
d=np.arange(1,7,1)

In [182]:
d

array([1, 2, 3, 4, 5, 6])

In [183]:
d.shape

(6,)

In [184]:
d.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [186]:
d.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [187]:
d.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [188]:
d.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6]])

In [193]:
d.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

- d 자체를 바꿔주는 건 아님

In [194]:
e=d.reshape(2,3)

In [195]:
f=np.linspace(1,10,10)

In [196]:
f

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [197]:
g=np.linspace(1,10,10).reshape(2,5)

In [198]:
g

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [199]:
a=np.array([[1,2],[3,4]])#2차원

In [200]:
a

array([[1, 2],
       [3, 4]])

In [201]:
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [205]:
np.repeat(a,2,axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [206]:
np.repeat(a,2,axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [207]:
#첫번째 줄은 한 번 반복하고 두번째 줄이 두 번 반복하라
np.repeat(a,[1,2],axis=0)

array([[1, 2],
       [3, 4],
       [3, 4]])

In [208]:
np.repeat(a,[3,1],axis=0)

array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4]])

In [209]:
np.repeat(a,[1,2],axis=1)

array([[1, 2, 2],
       [3, 4, 4]])

In [210]:
np.repeat(a,[3,1],axis=1)

array([[1, 1, 1, 2],
       [3, 3, 3, 4]])

In [211]:
a=np.array([[1],[2],[3]])
b=np.array([[4],[5],[6]])

In [214]:
a.shape

(3, 1)

In [215]:
b.shape

(3, 1)

- 둘다 차원은 2차원

In [217]:
np.concatenate((a,b),axis=0) # array 두개 연결

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [218]:
np.concatenate((a,b),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

- (a,b)이렇게 tuple 형태로 입력해줘야 함

In [219]:
a=np.array([10,20,30])
b=np.array([40,50,60])

In [220]:
# vertical stack
np.vstack((a,b))

array([[10, 20, 30],
       [40, 50, 60]])

In [221]:
# 가로로 연결
np.hstack((a,b))

array([10, 20, 30, 40, 50, 60])

In [222]:
a=np.array([[10,20,30],[40,50,60]])

In [223]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [226]:
# np.hsplit(a,2)
# 오류 발생, 왜? 세로 방향으로 2개로 나눌 수가 없어서

In [227]:
a=np.hsplit(a,3)

In [228]:
a

[array([[10],
        [40]]),
 array([[20],
        [50]]),
 array([[30],
        [60]])]

In [57]:
a[0]

array([[10],
       [40]])

In [224]:
a=np.array([[10,20,30],[40,50,60]])

In [225]:
np.vsplit(a,2)

[array([[10, 20, 30]]), array([[40, 50, 60]])]

이것또한 list로 저장 됨

어레이를 조각조각내서 리스트 안에 넣어줬기 때문에

그 조각을 살펴보면 np.array 형태이고 

그 조각들을 list안에 넣어준 것

In [230]:
a=np.array([[10,20,30],[40,50,60]])

In [231]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [233]:
# 전치행렬
a.transpose()

array([[10, 40],
       [20, 50],
       [30, 60]])

- 2차원의 array를 1차원의 array로 변경해보자

In [234]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [235]:
a.ravel()

array([10, 20, 30, 40, 50, 60])

In [238]:
a.reshape(-1)

array([10, 20, 30, 40, 50, 60])

In [243]:
a.ravel(order='C')   

array([10, 20, 30, 40, 50, 60])

In [244]:
a.ravel(order='F')   

array([10, 40, 20, 50, 30, 60])

In [245]:
a.flatten()

array([10, 20, 30, 40, 50, 60])

In [258]:
a=np.array([[1],[2],[3]]) # 2차원 형태로 넣어줌

In [259]:
a

array([[1],
       [2],
       [3]])

In [262]:
a_=np.array([[1,2,3]])

In [264]:
a_

array([[1, 2, 3]])

In [265]:
a__=np.array([1,2,3]) # 1차원 형태로 넣어줌

In [266]:
a__

array([1, 2, 3])

> ### `차이점`

In [267]:
a_[0]

array([1, 2, 3])

In [268]:
a[0][0]

1

----

In [269]:
a.ndim

2

In [271]:
a.shape

(3, 1)

In [272]:
a_.shape

(1, 3)

In [273]:
a__.shape

(3,)

In [274]:
a

array([[1],
       [2],
       [3]])

2차원에서 1차원으로 줄이자

In [276]:
b=a.squeeze()

In [277]:
b

array([1, 2, 3])

In [278]:
b.ndim

1

In [279]:
b.shape

(3,)

In [280]:
a=np.array([[[1,2]],[[3,4]],[[5,6]]])

In [281]:
a

array([[[1, 2]],

       [[3, 4]],

       [[5, 6]]])

In [282]:
a.shape

(3, 1, 2)

In [283]:
a.ndim

3

In [284]:
b=a.squeeze()

In [285]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [286]:
b.shape

(3, 2)

In [287]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [292]:
a

array([1, 2, 3])

In [288]:
a.shape

(3,)

In [289]:
a_=a[:,np.newaxis]
b_=b[:,np.newaxis]
# 차원 하나 추가

In [290]:
a_.shape

(3, 1)

In [291]:
a_

array([[1],
       [2],
       [3]])

In [293]:
np.concatenate((a_,b_),axis=0)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [294]:
np.concatenate((a_,b_),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [295]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [296]:
np.vstack((a,b)).transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [297]:
np.hstack((a,b)).reshape((2,3)).transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

> ### ***`shallow copy & deep copy`***

In [298]:
a=np.array([10,20,30])

In [299]:
b=a

In [300]:
b

array([10, 20, 30])

In [301]:
b[0]=909

In [302]:
b

array([909,  20,  30])

In [303]:
a

array([909,  20,  30])

In [304]:
b is a

True

- 즉 같은 메모리에 이름만 다르게 저장된 것

In [305]:
a=np.array([1,2,3,4])

In [306]:
b=a.view()

In [307]:
b

array([1, 2, 3, 4])

In [308]:
b is a

False

- 일단 메모리는 달라졌음

In [311]:
b[0]=123123

In [312]:
a

array([123123,      2,      3,      4])

In [313]:
b

array([123123,      2,      3,      4])

- `shallow copy`를 했음에도 같이 업데이트 되어버림

In [314]:
b.shape=(2,2)

In [315]:
b

array([[123123,      2],
       [     3,      4]])

In [316]:
b[0][1]=111

In [317]:
b

array([[123123,    111],
       [     3,      4]])

In [318]:
a

array([123123,    111,      3,      4])

- 즉 shallow copy란 메모리 상에 data는 같이 공유하지만 array의 shape은 공유 X

- 그렇다면 deep copy?

In [319]:
a=np.array([10,20,30,40])

In [320]:
b=a.copy()

In [321]:
b[0]=8999

In [322]:
a

array([10, 20, 30, 40])

In [323]:
b

array([8999,   20,   30,   40])

In [324]:
a is b

False

In [325]:
b.base is a

False

> `즉 b만의 온전한 데이터를 만들 수 있음`

----

In [326]:
a=np.array([55,0,12,3,4])

In [327]:
# a의 모든 값이 참?
# 여기선 0, 즉 FALSE값이 들어있기 때문에 FALSE로 나올 것
a.all()

False

In [328]:
# 하나라도 참이 들어있는지?
a.any()

True

In [329]:
# 0이 아닌 값들의 index를 알 수 있음
a.nonzero()

(array([0, 2, 3, 4], dtype=int64),)

In [330]:
# 0보다 큰 거 어디? index로 알려줄 것
np.where(a>0)

(array([0, 2, 3, 4], dtype=int64),)

In [331]:
np.where(a==0)

(array([1], dtype=int64),)

In [332]:
np.where(a!=0)

(array([0, 2, 3, 4], dtype=int64),)