# 2021/12/27/MON

In [1]:
import numpy as np
x_list=[1,2,3]
x_tuple=1,2,3
x_set={1,2,3}
x_dict={'a' : 1,'b' : 2,'c' : 3}
x_array=np.array([1,2,3])
x_range=range(1,4,1)

In [2]:
for i in x_dict:
    print(i)

a
b
c


- key만 나왔음, 후에 부가 설명하겠음

In [8]:
import time
for i in [1,2,3]:
    print('i=' + str(i))
    time.sleep(.5)

i=1
i=2
i=3


- 이때 i는 마지막 값인 3으로 저장될 것

---

1부터 100까지 = range(1,100,1)

range(101)은 0부터 100까지임

또는 np.linspace(1,100,100)으로도 사용가능

---

iterable object이 str일 땐?

In [9]:
for i in '12345':
    print(i)

1
2
3
4
5


In [10]:
for i in 'python':
    print(i)

p
y
t
h
o
n


In [11]:
for i in {1,2,3,4,5}:
    print(i)

1
2
3
4
5


---

In [12]:
d={'P1':11,'P3':31,'P2':13}

In [17]:
d.items()

dict_items([('P1', 11), ('P3', 31), ('P2', 13)])

In [18]:
d.keys()

dict_keys(['P1', 'P3', 'P2'])

In [19]:
d.values()

dict_values([11, 31, 13])

---

In [20]:
for i in d.items():
    print(i)

('P1', 11)
('P3', 31)
('P2', 13)


In [21]:
for i in d.keys():
    print(i)

P1
P3
P2


In [22]:
for i in d.values():
    print(i)

11
31
13


In [23]:
for i in np.array([1,2,3]):
    print(i)

1
2
3


---

> ### `반복문 중첩`

In [24]:
for i in range(1,4,1):
    for j in [1,2]:
        print('i*j={}*{}={}'.format(i,j,i*j))

i*j=1*1=1
i*j=1*2=2
i*j=2*1=2
i*j=2*2=4
i*j=3*1=3
i*j=3*2=6


---

반복문은 iterable일 때 사용가능, then what is iterable??

In [34]:
x_list=[1,2,3]

In [35]:
x_iter=iter(x_list)

In [36]:
next(x_iter)
# 하나하나 차례로 나올 것, 그리고 마지막엔 오류

1

`값을 하나씩 불러온다는 것만 알아두자`

---


In [42]:
for i in range(3):
    print('여긴 적용 O')
    time.sleep(0.2)
print('-----------')
print('여긴 적용 X')

여긴 적용 O
여긴 적용 O
여긴 적용 O
-----------
여긴 적용 X


---

In [44]:
m=np.array([1,2,3])
n=['sd','asd','asdd']
q={'a':11,'d':22,'c':123}

In [48]:
# 인덱싱 번호랑 그 원소랑 짝 지어서!
for i,v in enumerate(n):
    print(i,v)
    print(' ')

0 sd
 
1 asd
 
2 asdd
 


In [49]:
q

{'a': 11, 'd': 22, 'c': 123}

In [51]:
for i,v in enumerate(q.items()):
    print(i)
    print(v)
    print(' ')

0
('a', 11)
 
1
('d', 22)
 
2
('c', 123)
 


- 인덱스를 1부터 시작하게 해서 count할 수 있음

In [52]:
for i,v in enumerate(m,start=1):
    print(i)
    print(v)
    print(' ')

1
1
 
2
2
 
3
3
 


반복문이 3번 실행됐음을 알 수 있다. 

----

In [54]:
m

array([1, 2, 3])

In [55]:
n

['sd', 'asd', 'asdd']

In [59]:
q

{'a': 11, 'd': 22, 'c': 123}

In [56]:
for i in zip(m,n):
    print(i)

(1, 'sd')
(2, 'asd')
(3, 'asdd')


In [57]:
for i in zip(m,n):
    print(list(i))

[1, 'sd']
[2, 'asd']
[3, 'asdd']


In [58]:
for i in zip(m,n,q.items()):
    print(list(i))

[1, 'sd', ('a', 11)]
[2, 'asd', ('d', 22)]
[3, 'asdd', ('c', 123)]


----

> `반복문 활용 예시`

In [60]:
s='♡Best Company♡  Tel: 123-123123'
for i in range(5):
    print(s)
    print(' ')

♡Best Company♡  Tel: 123-123123
 
♡Best Company♡  Tel: 123-123123
 
♡Best Company♡  Tel: 123-123123
 
♡Best Company♡  Tel: 123-123123
 
♡Best Company♡  Tel: 123-123123
 


In [62]:
x=np.array([1,2,3,4,5])
for i in x:
    print(i**2)
    time.sleep(0.5)

1
4
9
16
25


In [65]:
x=np.array([1,2,3,4,5])
for i,x in enumerate(x,start=1):
    print(i)
    print(x)
    print('')

1
1

2
2

3
3

4
4

5
5



In [66]:
x=np.array([1,2,3,4,5])
y=np.zeros(x.shape)
for i,x in enumerate(x):
    y[i]=x**2
    print(y)

[1. 0. 0. 0. 0.]
[1. 4. 0. 0. 0.]
[1. 4. 9. 0. 0.]
[ 1.  4.  9. 16.  0.]
[ 1.  4.  9. 16. 25.]


---

> 피보나치 수열 : 앞 숫자를 계속 더해주는 수열

In [71]:
a=np.array([0,1])
for i in range(5):
    a=np.append(a,a[-1]+a[-2])
    print(a)

[0 1 1]
[0 1 1 2]
[0 1 1 2 3]
[0 1 1 2 3 5]
[0 1 1 2 3 5 8]


---

- 피보나치 수열의 또 다른 표현

In [74]:
a,b=0,1
for i in range(5):
    print(a)
    a,b=b,a+b

0
1
1
2
3


---

> ### `***조건문`

In [75]:
x=input('Type any number: ')
if x.isdigit():
    y=int(x)+1
    print('Result is {}'.format(y))
else : print('정수 쳐 넣어')

Type any number:  564


Result is 565


- 첫번째 줄에서 입력되는 것이 숫자인지 문자인지? $\to$ bool형으로 반환 필요 $\to$ isdigit을 이용!!

In [77]:
x=input('Type any number: ')
while x.isdigit() != True :
    x=input('Try again: ')
y=int(x)+1
print('Result is {}'.format(y))

Type any number:  ㅁㄴㅇ
Try again:  ㅁㄴㅇㅁㄴ
Try again:  ㅊㅁㅇㅍ
Try again:  아니 시
Try again:  아하
Try again:  fasle나올 때까지 반복할 모양임
Try again:  123


Result is 124


while문 => 무한 반복(참인 경우에 한해서)

In [84]:
x=int(input('몇살이니? : '))
if x>=18 : 
    print('면허 딸 수 있겠다')
elif x>=15 & x<18 :
    print('승인은 가능하겠다')
else : 
    print('나이가 어려서 안 돼')

몇살이니? :  15


승인은 가능하겠다


In [83]:
x=int(input('몇살이니? : '))
if x>=18 : 
    print('면허 딸 수 있겠다')
elif x>=15 and x<18 :
    print('승인은 가능하겠다')
else : 
    print('나이가 어려서 안 돼')

몇살이니? :  15


승인은 가능하겠다


----

In [85]:
a=['a','b','c','d']
check=input('please name: ')
if check in a :
    print('어서와' +" " + check+'야')
else : print('넌 명단에 없네')

please name:  a


어서와 a야


----

> `While`

In [86]:
vip=['a','b','c','d']
a=[1,2]
a_=[]

In [87]:
bool(a)

True

In [88]:
bool(a_)

False

while은 참일때만 실행하니까 vip리스트에 하나도 없으면, 즉 FALSE이면 실행 멈출 것

In [89]:
while vip:
    print(vip.pop(0))
    print('remaining guest #: {}'.format(len(vip)))

a
remaining guest #: 3
b
remaining guest #: 2
c
remaining guest #: 1
d
remaining guest #: 0


In [90]:
a=list([1,2,3,4,5])

In [91]:
a.pop(3)

4

In [92]:
a

[1, 2, 3, 5]

- pop함수 : 해당 인덱스 원소를 삭제하면서 삭제되는 원소도 반환시켜줌

---

In [93]:
balance=10000 # 가지고 있는 돈
interest=0.05 # 이자율
yr=0 # 시작 연도

# 통장에 10000원 넣어놓고 몇년이 지나야 20000원이 될까?

In [94]:
while balance < 20000:
    balance=balance*(1+interest)
    yr+=1
    print('Year: {}'.format(yr))
    print('Current values= {}'.format(balance))

Year: 1
Current values= 10500.0
Year: 2
Current values= 11025.0
Year: 3
Current values= 11576.25
Year: 4
Current values= 12155.0625
Year: 5
Current values= 12762.815625000001
Year: 6
Current values= 13400.956406250001
Year: 7
Current values= 14071.004226562502
Year: 8
Current values= 14774.554437890627
Year: 9
Current values= 15513.28215978516
Year: 10
Current values= 16288.946267774418
Year: 11
Current values= 17103.393581163138
Year: 12
Current values= 17958.563260221297
Year: 13
Current values= 18856.491423232364
Year: 14
Current values= 19799.315994393983
Year: 15
Current values= 20789.281794113682


---

즉 15년까지 while이 진행됐다는 건 15년째 20000을 넘었기 때문에 다음 16이 진행 안 된 것 ,

따라서 15년때 20000을 넘은 것을 알 수 있음

---


In [95]:
for i in range(5):
    print(i)
    if i ==3 : break

0
1
2
3


In [96]:
balance=10000 # 가지고 있는 돈
interest=0.05 # 이자율
yr=0 # 시작 연도

for i in range(10000):
    balance=balance*(1+interest)
    yr+=1
    print('# of Year : {}'.format(yr))
    print('Current values= {}'.format(balance))
    if balance >20000 : break

# of Year : 1
Current values= 10500.0
# of Year : 2
Current values= 11025.0
# of Year : 3
Current values= 11576.25
# of Year : 4
Current values= 12155.0625
# of Year : 5
Current values= 12762.815625000001
# of Year : 6
Current values= 13400.956406250001
# of Year : 7
Current values= 14071.004226562502
# of Year : 8
Current values= 14774.554437890627
# of Year : 9
Current values= 15513.28215978516
# of Year : 10
Current values= 16288.946267774418
# of Year : 11
Current values= 17103.393581163138
# of Year : 12
Current values= 17958.563260221297
# of Year : 13
Current values= 18856.491423232364
# of Year : 14
Current values= 19799.315994393983
# of Year : 15
Current values= 20789.281794113682


> 즉 15는 20000을 넘어서 break된 것을 알 수 있음

----

In [97]:
for i in range(5):
    continue
    print(i)

왜 아무것도 출력 X ?

- 반복문은 다섯번 반복됐으나 그럴 때마다 continue를 만나서 다시 위로 올라가서 반복했기 때문

- 이런 기능을 가진 continue를 이렇게 활용해보자

In [98]:
for i in range(5):
    if i==2 : continue
    print(i)

0
1
3
4


---

In [99]:
temp=[18,19,20,-10,-20,-30]

In [100]:
for t in temp:
    print('T={}'.format(t))

T=18
T=19
T=20
T=-10
T=-20
T=-30


- continue 이렇게 활용하자!

- 이때 -값은 오류라고 생각하고 print하고 싶지 않을 땐?

In [102]:
for t in temp:
    if t<0 :
        continue
    print('T={}'.format(t))

T=18
T=19
T=20


---

In [103]:
for x in range(5):
    pass
x=1

In [104]:
x

1

In [105]:
if True:
    pass
x=1

In [106]:
x

1

In [107]:
def myfun():
    pass
a=23

In [108]:
a

23

그냥 일단 패스시켜놓고 나중에 완성 시키고 싶을 때

---

> 예외처리?

In [109]:
age=int(input('몇살이니?: '))
print('Age={}'.format(age))

몇살이니?:  5645


Age=5645


- 만약 여기서 숫자가 아닌 문자를 넣으면 value error가 발생할 것

In [111]:
while True:
    try:
        age=int(input('몇살이니?: '))
        print('Age={}'.format(age))
        break
    except ValueError:
        print('숫자를 입력해주세요')

몇살이니?:  ㅁㄴ


숫자를 입력해주세요


몇살이니?:  ㅁㅇ


숫자를 입력해주세요


몇살이니?:  56


Age=56


숫자를 입력할 때까지 while문이 실행될 것

In [120]:
a=np.array([10,20,30,40,50,-80])
num_max=np.NINF # 음의 무한대를 의미함
for i in a:
    num_curr = i
    if num_max < num_curr:
        num_max=num_curr

In [121]:
num_max

50

-80은 실행 X

---

In [122]:
a=np.array([1,2,3,4,5,6])
for i in a:
    if i%2==0:
        print('{}는 짝수'.format(i))
    else : print('{}는 홀수'.format(i))

1는 홀수
2는 짝수
3는 홀수
4는 짝수
5는 홀수
6는 짝수


---

> User Interface Example/ `UI`

In [123]:
db={'a':'a1','b':'b1','c':'c1'}
password_attemps=3
while password_attemps > 0 :
    user_id = input('ID: ')
    user_ps = input('PW: ')
    if user_id in db.keys() and \
    user_ps in db.values() :
        print('\nLog in Successful!')
        break
    else:
        password_attemps-=1
        print('\n까먹음? 다시 시도 ㄱㄱ')
        print('{} 번 더 시도 가능'.format(password_attemps))

ID:  45
PW:  45



까먹음? 다시 시도 ㄱㄱ
2 번 더 시도 가능


ID:  45
PW:  45



까먹음? 다시 시도 ㄱㄱ
1 번 더 시도 가능


ID:  45
PW:  45



까먹음? 다시 시도 ㄱㄱ
0 번 더 시도 가능


> 여기서는 구현하지 않았지만 import getpass 기능을 이용해서 password입력 할 때 해당 PW를 안 보이게 해줄 수 있음

---

In [127]:
my_str='python'
my_str2=[]
for letter in my_str:
    my_str2.append(letter)

In [128]:
my_str

'python'

In [129]:
my_str2

['p', 'y', 't', 'h', 'o', 'n']

$\to$ 이걸 한 줄로 가능하게 하는 것이 List Comprehension

In [130]:
my_str3=[letter for letter in my_str]
my_str3

['p', 'y', 't', 'h', 'o', 'n']

> `list comprehension` $+$ `조건`

In [131]:
num=[a for a in range(20) if a%2==0]

In [132]:
num

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [133]:
num=[a for a in range(20) if a%2!=0]

In [134]:
num

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [135]:
num=[a for a in range(50) if a%5==0 and a%2==0]

In [136]:
num

[0, 10, 20, 30, 40]

또는

In [137]:
num=[a for a in range(50) if a%5==0
     if a%2==0]

In [138]:
num

[0, 10, 20, 30, 40]

---

차이점!!!

In [143]:
num=[a for a in range(50) if a%5==0 and a%2==0]

In [144]:
num

[0, 10, 20, 30, 40]

In [149]:
num=[a for a in range(50) if a%5==0 if a%2==0]

In [150]:
num

[0, 10, 20, 30, 40]

In [151]:
num=[a for a in range(50) if a%5==0 & a%2==0]

In [152]:
num

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45]

차이점 꼭!!!!!! 

----

In [153]:
aaa=['짝수'if i%2==0 else '홀수' for i in range(10)]

In [154]:
aaa

['짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수']

---

> `dict comprehension`

In [155]:
a={i:i**2 for i in range(6)}
a

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25}

---

In [156]:
import sys,os

In [157]:
print(os.getcwd())

C:\Users\ehfus\Downloads\python Introduction


In [276]:
os.mkdir('my_dir')
# 현재 있는 위치에서 my_dir을 하나 만듦

In [277]:
os.chdir('.\my_dir')

파일 100개 만들어보자

In [279]:
for i in range(100):
    f=open('NewFile'+str(i),'w') # 파일을 쓸 거니까 'w'
    f.close()

100개의 파일에 뭘 쓰진 않았음. 이제 파일의 이름을 바꿔보자

반복문을 통해 100개의 파일 이름을 바꾸기 전에 100개 파일의 이름을 일단 받아오자

In [281]:
flist=os.listdir('.')

In [282]:
flist

['NewFile0',
 'NewFile1',
 'NewFile10',
 'NewFile11',
 'NewFile12',
 'NewFile13',
 'NewFile14',
 'NewFile15',
 'NewFile16',
 'NewFile17',
 'NewFile18',
 'NewFile19',
 'NewFile2',
 'NewFile20',
 'NewFile21',
 'NewFile22',
 'NewFile23',
 'NewFile24',
 'NewFile25',
 'NewFile26',
 'NewFile27',
 'NewFile28',
 'NewFile29',
 'NewFile3',
 'NewFile30',
 'NewFile31',
 'NewFile32',
 'NewFile33',
 'NewFile34',
 'NewFile35',
 'NewFile36',
 'NewFile37',
 'NewFile38',
 'NewFile39',
 'NewFile4',
 'NewFile40',
 'NewFile41',
 'NewFile42',
 'NewFile43',
 'NewFile44',
 'NewFile45',
 'NewFile46',
 'NewFile47',
 'NewFile48',
 'NewFile49',
 'NewFile5',
 'NewFile50',
 'NewFile51',
 'NewFile52',
 'NewFile53',
 'NewFile54',
 'NewFile55',
 'NewFile56',
 'NewFile57',
 'NewFile58',
 'NewFile59',
 'NewFile6',
 'NewFile60',
 'NewFile61',
 'NewFile62',
 'NewFile63',
 'NewFile64',
 'NewFile65',
 'NewFile66',
 'NewFile67',
 'NewFile68',
 'NewFile69',
 'NewFile7',
 'NewFile70',
 'NewFile71',
 'NewFile72',
 'NewFile73',


In [283]:
for fid in flist:
    f_name=fid[0:7]
    f_num=fid[7::]
    if int(f_num)<50:
        os.replace(fid,'2019_'+fid)
    else:
        os.replace(fid,'2020_'+fid)

2019년도 파일 2020년도 파일을 두개의 디렉토리에 각각 넣어보자

In [284]:
os.mkdir('2019_data')
os.mkdir('2020_data')

In [287]:
flist=os.listdir('.')

In [310]:
flist

['2019_data',
 '2019_NewFile0',
 '2019_NewFile1',
 '2019_NewFile10',
 '2019_NewFile11',
 '2019_NewFile12',
 '2019_NewFile13',
 '2019_NewFile14',
 '2019_NewFile15',
 '2019_NewFile16',
 '2019_NewFile17',
 '2019_NewFile18',
 '2019_NewFile19',
 '2019_NewFile2',
 '2019_NewFile20',
 '2019_NewFile21',
 '2019_NewFile22',
 '2019_NewFile23',
 '2019_NewFile24',
 '2019_NewFile25',
 '2019_NewFile26',
 '2019_NewFile27',
 '2019_NewFile28',
 '2019_NewFile29',
 '2019_NewFile3',
 '2019_NewFile30',
 '2019_NewFile31',
 '2019_NewFile32',
 '2019_NewFile33',
 '2019_NewFile34',
 '2019_NewFile35',
 '2019_NewFile36',
 '2019_NewFile37',
 '2019_NewFile38',
 '2019_NewFile39',
 '2019_NewFile4',
 '2019_NewFile40',
 '2019_NewFile41',
 '2019_NewFile42',
 '2019_NewFile43',
 '2019_NewFile44',
 '2019_NewFile45',
 '2019_NewFile46',
 '2019_NewFile47',
 '2019_NewFile48',
 '2019_NewFile49',
 '2019_NewFile5',
 '2019_NewFile6',
 '2019_NewFile7',
 '2019_NewFile8',
 '2019_NewFile9',
 '2020_data',
 '2020_NewFile50',
 '2020_NewFil

In [311]:
from itertools import compress

In [312]:
idx = list(map(lambda x:'File' in x, flist))
flist2 = list(compress(flist,idx))

In [313]:
flist2

['2019_NewFile0',
 '2019_NewFile1',
 '2019_NewFile10',
 '2019_NewFile11',
 '2019_NewFile12',
 '2019_NewFile13',
 '2019_NewFile14',
 '2019_NewFile15',
 '2019_NewFile16',
 '2019_NewFile17',
 '2019_NewFile18',
 '2019_NewFile19',
 '2019_NewFile2',
 '2019_NewFile20',
 '2019_NewFile21',
 '2019_NewFile22',
 '2019_NewFile23',
 '2019_NewFile24',
 '2019_NewFile25',
 '2019_NewFile26',
 '2019_NewFile27',
 '2019_NewFile28',
 '2019_NewFile29',
 '2019_NewFile3',
 '2019_NewFile30',
 '2019_NewFile31',
 '2019_NewFile32',
 '2019_NewFile33',
 '2019_NewFile34',
 '2019_NewFile35',
 '2019_NewFile36',
 '2019_NewFile37',
 '2019_NewFile38',
 '2019_NewFile39',
 '2019_NewFile4',
 '2019_NewFile40',
 '2019_NewFile41',
 '2019_NewFile42',
 '2019_NewFile43',
 '2019_NewFile44',
 '2019_NewFile45',
 '2019_NewFile46',
 '2019_NewFile47',
 '2019_NewFile48',
 '2019_NewFile49',
 '2019_NewFile5',
 '2019_NewFile6',
 '2019_NewFile7',
 '2019_NewFile8',
 '2019_NewFile9',
 '2020_NewFile50',
 '2020_NewFile51',
 '2020_NewFile52',
 '2

dir이름은 없고 파일이름만 뽑아온 것

두번째 방법

In [314]:
flist3=list(filter(lambda x: 'File' in x, flist))

In [316]:
flist3

['2019_NewFile0',
 '2019_NewFile1',
 '2019_NewFile10',
 '2019_NewFile11',
 '2019_NewFile12',
 '2019_NewFile13',
 '2019_NewFile14',
 '2019_NewFile15',
 '2019_NewFile16',
 '2019_NewFile17',
 '2019_NewFile18',
 '2019_NewFile19',
 '2019_NewFile2',
 '2019_NewFile20',
 '2019_NewFile21',
 '2019_NewFile22',
 '2019_NewFile23',
 '2019_NewFile24',
 '2019_NewFile25',
 '2019_NewFile26',
 '2019_NewFile27',
 '2019_NewFile28',
 '2019_NewFile29',
 '2019_NewFile3',
 '2019_NewFile30',
 '2019_NewFile31',
 '2019_NewFile32',
 '2019_NewFile33',
 '2019_NewFile34',
 '2019_NewFile35',
 '2019_NewFile36',
 '2019_NewFile37',
 '2019_NewFile38',
 '2019_NewFile39',
 '2019_NewFile4',
 '2019_NewFile40',
 '2019_NewFile41',
 '2019_NewFile42',
 '2019_NewFile43',
 '2019_NewFile44',
 '2019_NewFile45',
 '2019_NewFile46',
 '2019_NewFile47',
 '2019_NewFile48',
 '2019_NewFile49',
 '2019_NewFile5',
 '2019_NewFile6',
 '2019_NewFile7',
 '2019_NewFile8',
 '2019_NewFile9',
 '2020_NewFile50',
 '2020_NewFile51',
 '2020_NewFile52',
 '2

세번째 방법

In [318]:
file4=[x for x in flist if 'File' in x]

네번째 방법

In [321]:
import glob
glob.glob('2020_NewFile??')

['2020_NewFile50',
 '2020_NewFile51',
 '2020_NewFile52',
 '2020_NewFile53',
 '2020_NewFile54',
 '2020_NewFile55',
 '2020_NewFile56',
 '2020_NewFile57',
 '2020_NewFile58',
 '2020_NewFile59',
 '2020_NewFile60',
 '2020_NewFile61',
 '2020_NewFile62',
 '2020_NewFile63',
 '2020_NewFile64',
 '2020_NewFile65',
 '2020_NewFile66',
 '2020_NewFile67',
 '2020_NewFile68',
 '2020_NewFile69',
 '2020_NewFile70',
 '2020_NewFile71',
 '2020_NewFile72',
 '2020_NewFile73',
 '2020_NewFile74',
 '2020_NewFile75',
 '2020_NewFile76',
 '2020_NewFile77',
 '2020_NewFile78',
 '2020_NewFile79',
 '2020_NewFile80',
 '2020_NewFile81',
 '2020_NewFile82',
 '2020_NewFile83',
 '2020_NewFile84',
 '2020_NewFile85',
 '2020_NewFile86',
 '2020_NewFile87',
 '2020_NewFile88',
 '2020_NewFile89',
 '2020_NewFile90',
 '2020_NewFile91',
 '2020_NewFile92',
 '2020_NewFile93',
 '2020_NewFile94',
 '2020_NewFile95',
 '2020_NewFile96',
 '2020_NewFile97',
 '2020_NewFile98',
 '2020_NewFile99']

이런식으로

In [325]:
file5=glob.glob('*File*')

----

> 이제 파일들을 각 년도 dir에 넣어보자

In [327]:
import shutil

In [330]:
for f_curr in file5:
    f_name = f_curr[0:12]
    f_num = f_curr[12::]
    if int(f_num) < 50:
        shutil.move(f_curr,'.\\2019_data')
    else:
        shutil.move(f_curr,'.\\2020_data')

dir에 파일들이 각각 들어갔음