# 2022/12/24/FRI

In [1]:
import numpy as np

In [2]:
np.linspace(0,4,5)

array([0., 1., 2., 3., 4.])

In [22]:
np.arange(10) # 0부터 10개의 숫자

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a=np.array([10,20,3])

In [28]:
a.shape 
# array의 shape을 알려줌
# 1차원 행렬에 방 세개

(3,)

In [31]:
a.ndim #1차원

1

In [33]:
a.dtype #array에 들어간 숫자들이 어떤 형식으로?

dtype('int32')

In [36]:
a.itemsize # 4byte 32=4*8

4

In [38]:
a.size #몇개 들어가 있니

3

In [41]:
type(a) #몇차원이고 될 수 있음, nd=ndimension

numpy.ndarray

- np.array도 sequence 타입 => index,slicing가능

In [51]:
a[2]

3

In [52]:
a[2]=30.8

In [53]:
a

array([10, 20, 30])

> `소수점 날라가고 30으로 저장됨` 

In [55]:
a.dtype

dtype('int32')

In [59]:
a=a.astype('float64')

In [60]:
a[2]=30.865

In [61]:
a

array([10.   , 20.   , 30.865])

In [62]:
a.dtype

dtype('float64')

- 소수점도 가능한 자료형으로 변경해줬음

In [63]:
b=np.array([10.,20.,30.])

In [64]:
b.dtype

dtype('float64')

> 애초에 이렇게 dot을 지정해주고 들어가면 float으로 활용가능

In [65]:
c=np.array([10.2,20.3,50.58],'int32')

In [66]:
c

array([10, 20, 50])

> 이렇게 'int32'로 지정해줄 수 있음

In [67]:
x=np.array([7,9,11])
y=x/2

In [68]:
y

array([3.5, 4.5, 5.5])

In [70]:
x.dtype

dtype('int32')

In [71]:
y.dtype

dtype('float64')

> x가 정수로 시작했어도 y는 divide를 사용하고 있기에 알아서 np에서 float64로 지정함

##### `int32` $vs$ `int64`

In [80]:
x=np.array([0])

In [81]:
x[0]=2147483647

In [82]:
x

array([2147483647])

In [83]:
x[0]=x[0]+1

C:\Users\ehfus\AppData\Local\Temp/ipykernel_11512/4237261130.py:1: RuntimeWarning: overflow encountered in long_scalars
  x[0]=x[0]+1


> 2147483647은 int32에서 수용할 수 있는 최대의 숫자임, 따라서 여기서 1만 더해주더라도 수용하지 못하게 됨

In [84]:
x=np.array([0],'int64')

In [85]:
x[0]=2147483647

In [86]:
x[0]+1

2147483648

> dtype을 int64로 바꿨기 때문에 int32에서 최대였던 것보다 더 수용할 수 있게 됨

In [89]:
a=np.array([10,'abc',20]) # 꼭 list형태로 줘야 함
    

In [91]:
a.dtype #섞여있음

dtype('<U11')

In [93]:
a*2

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U11'), dtype('int32')) -> None

> 섞여있으면 이런 연산은 불가

In [95]:
a=np.array([[10,20,30],[40,50,60]])

In [97]:
a # 2차원

array([[10, 20, 30],
       [40, 50, 60]])

In [100]:
a.shape # 2x3행렬로 해석해도 될듯

(2, 3)

In [99]:
a.itemsize

4

In [101]:
a.size

6

In [102]:
a=np.array([[10,20,30],[40,50,60],[5,6,8]])

In [103]:
a

array([[10, 20, 30],
       [40, 50, 60],
       [ 5,  6,  8]])

In [104]:
a.size

9

In [106]:
a=np.array([[10,20,30],
            [40,50,60],
           [55,54,88]
            ,[112,123,41]])

In [111]:
a

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 55,  54,  88],
       [112, 123,  41]])

In [112]:
a.ndim

2

In [109]:
a.shape

(4, 3)

In [113]:
a=np.array([10+10j,10+60j])

In [114]:
a

array([10.+10.j, 10.+60.j])

In [115]:
a=np.array([10,20],'complex')

In [116]:
a

array([10.+0.j, 20.+0.j])

---

In [118]:
a=np.array([10,20])

In [119]:
b=np.matrix([10,20])

In [121]:
a.ndim

1

In [122]:
b.ndim

2

In [123]:
b=np.matrix([[[10]]])

ValueError: matrix must be 2-dimensional

2차원을 넘어간 3차원이기에 불가능

In [124]:
a=np.array([10,20,30])

In [129]:
a=np.insert(a,2,5)
# a라는 np.array의 2번째 인덱스에 5를 넣어라

In [130]:
a

array([ 5, 10,  5,  5, 20, 30])

In [131]:
a=np.delete(a,5)

In [133]:
a # 다섯번째 인덱스 삭제

array([ 5, 10,  5,  5, 20])

In [134]:
a=np.array([1,2,3])

In [136]:
a=np.arange(3)

In [138]:
a # 0부터 시작해서 숫자 3개를 채워줌

array([0, 1, 2])

In [139]:
a=np.zeros((2,3))

In [140]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [141]:
a=np.ones((2,3))

In [142]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [154]:
a=np.linspace(0,5,4) #0부터 5까지 4개로

In [155]:
a

array([0.        , 1.66666667, 3.33333333, 5.        ])

In [156]:
a=np.linspace(0,5,6) #0부터 5까지 6개로

In [157]:
a

array([0., 1., 2., 3., 4., 5.])

In [162]:
a=np.logspace(0,5,4) # log scale로!

In [163]:
a

array([1.00000000e+00, 4.64158883e+01, 2.15443469e+03, 1.00000000e+05])

---

In [165]:
a=np.array([10,20,30])
b=np.array([1,2,3])

In [166]:
a+b

array([11, 22, 33])

In [167]:
a-b

array([ 9, 18, 27])

In [168]:
b-a

array([ -9, -18, -27])

In [169]:
a*b

array([10, 40, 90])

In [170]:
a/b

array([10., 10., 10.])

In [171]:
c=a**2

In [172]:
c

array([100, 400, 900], dtype=int32)

In [177]:
idx=a<20

In [178]:
idx

array([ True,  True,  True])

In [179]:
type(idx)

numpy.ndarray

In [180]:
a=a+1

In [181]:
a

array([2, 3, 4])

In [182]:
a+=1

In [183]:
a

array([3, 4, 5])

In [184]:
a*=2

In [185]:
a

array([ 6,  8, 10])

In [186]:
a=a*2

In [187]:
a

array([12, 16, 20])

In [190]:
a=np.array([10,50,9]) # int
b=np.array([50.,5.,8.]) #float

In [191]:
a+=b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

a에b를 더해서 a를 업데이트 하는 건 자료형이 달라서 안 된다고 함

되게 하려면 자료형을 맞춰주면 됨

In [197]:
c=a+b # 이건 됨

In [198]:
c

array([60., 55., 17.])

----

In [199]:
a=np.array([10,50,9]) 
b=np.array([50,5,8]) 

In [200]:
np.add(a,b)

array([60, 55, 17])

In [201]:
np.subtract(a,b)

array([-40,  45,   1])

In [202]:
np.divide(a,b)

array([ 0.2  , 10.   ,  1.125])

In [203]:
np.multiply(a,b)

array([500, 250,  72])

In [205]:
np.divmod(a,b) # 몫과 나머지 

(array([ 0, 10,  1], dtype=int32), array([10,  0,  1], dtype=int32))

In [206]:
np.exp(b)

array([5.18470553e+21, 1.48413159e+02, 2.98095799e+03])

In [207]:
np.sqrt(a)

array([3.16227766, 7.07106781, 3.        ])

----

In [208]:
a=np.array([10,20,3])

In [210]:
np.mean(a)

11.0

In [211]:
a.mean()

11.0

In [213]:
np.average(a)

11.0

In [215]:
# 머신러닝 학습시 가중치 주는 법
np.average(a,weights=[1,1,1])

11.0

In [216]:
np.average(a,weights=[1,1,0])

15.0

In [217]:
np.average(a,weights=[0,1,1])

11.5

In [218]:
np.median(a)

10.0

In [220]:
np.cumsum(a) # 앞에 있는 숫자들을 더해주는 것

array([10, 30, 33], dtype=int32)

In [221]:
np.cov(a)

array(73.)

In [222]:
np.std(a)

6.97614984548545

In [223]:
np.var(a)

48.666666666666664

In [224]:
x=np.array([10,20,30])

In [226]:
x.sum()

60

In [247]:
x=np.array([10.,40.,20.,5.,15.])

In [229]:
x.min()

10.0

In [230]:
x.max()

50.0

In [232]:
x.argmin() # index 0에 최솟값이 존재함

0

In [233]:
# 최솟값과 최솟값의 자릿값을 한 번에 알아보기a
x_min,x_min_idx=x.min(),x.argmin()

In [235]:
# ptp= peak-to-peak
# 최솟값과 최댓값의 차이
x.ptp()

40.0

In [248]:
y=np.sort(x)

In [249]:
y

array([ 5., 10., 15., 20., 40.])

In [250]:
idx = np.argsort(x)

In [251]:
idx

array([3, 0, 4, 2, 1], dtype=int64)

In [252]:
y

array([ 5., 10., 15., 20., 40.])

> sort된 값들이 원래 어디에 위치해 있었는지

In [253]:
x[idx]

array([ 5., 10., 15., 20., 40.])

In [254]:
y=x[idx]

In [255]:
y

array([ 5., 10., 15., 20., 40.])

In [258]:
a=np.array([20,10,30])
b=np.array([-5,25])

In [259]:
np.searchsorted(a,b)

array([0, 2], dtype=int64)

- b를 a에 넣을 때 어느 자리에 넣어야 sorting이 유지가 되는지?

In [2]:
d=np.arange(1,7,1)

In [8]:
d

array([1, 2, 3, 4, 5, 6])

In [9]:
d.shape

(6,)

In [11]:
d.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

- d 자체를 바꿔주는 건 아님

In [12]:
e=d.reshape(2,3)

In [13]:
f=np.linspace(1,10,10)

In [14]:
f

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [15]:
g=np.linspace(1,10,10).reshape(2,5)

In [16]:
g

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [18]:
a=np.array([[1,2],[3,4]])#2차원

In [20]:
a

array([[1, 2],
       [3, 4]])

In [19]:
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [21]:
np.repeat(a,2,axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [22]:
np.repeat(a,2,axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [24]:
#첫번째 줄은 한 번 반복하고 두번째 줄이 두 번 반복하라
np.repeat(a,[1,2],axis=0)

array([[1, 2],
       [3, 4],
       [3, 4]])

In [25]:
np.repeat(a,[3,1],axis=0)

array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4]])

In [26]:
np.repeat(a,[1,2],axis=1)

array([[1, 2, 2],
       [3, 4, 4]])

In [28]:
np.repeat(a,[3,1],axis=1)

array([[1, 1, 1, 2],
       [3, 3, 3, 4]])

In [29]:
a=np.array([[1],[2],[3]])
b=np.array([[4],[5],[6]])

In [30]:
a.shape

(3, 1)

In [31]:
b.shape

(3, 1)

In [33]:
np.concatenate((a,b),axis=0) # array 두개 연결

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [35]:
np.concatenate((a,b),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

- (a,b)이렇게 tuple 형태로 입력해줘야 함

In [36]:
a=np.array([10,20,30])
b=np.array([40,50,60])

In [39]:
# vertical stack
np.vstack((a,b))

array([[10, 20, 30],
       [40, 50, 60]])

In [41]:
# 가로로 연결
np.hstack((a,b))

array([10, 20, 30, 40, 50, 60])

In [47]:
a=np.array([[10,20,30],[40,50,60]])

In [49]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [50]:
# np.hsplit(a,2)
# 오류 발생, 왜? 세로 방향으로 2개로 나눌 수가 없어서

In [52]:
a=np.hsplit(a,3)

In [54]:
a

[array([[10],
        [40]]),
 array([[20],
        [50]]),
 array([[30],
        [60]])]

In [56]:
a.shape

AttributeError: 'list' object has no attribute 'shape'

보다시피 list안에 np.array가 들어갔음

In [57]:
a[0]

array([[10],
       [40]])

In [59]:
a=np.array([[10,20,30],[40,50,60]])

In [60]:
np.vsplit(a,2)

[array([[10, 20, 30]]), array([[40, 50, 60]])]

이것또한 list로 저장 됨

어레이를 조각조각내서 리스트 안에 넣어줬기 때문에

그 조각을 살펴보면 np.array 형태이고 

그 조각들을 list안에 넣어준 것

In [61]:
a=np.array([[10,20,30],[40,50,60]])

In [63]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [62]:
a.transpose()

array([[10, 40],
       [20, 50],
       [30, 60]])

2차원의 array를 1차원의 array로 변경

In [65]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [66]:
a.ravel()

array([10, 20, 30, 40, 50, 60])

In [68]:
a.reshape(-1)

array([10, 20, 30, 40, 50, 60])

In [69]:
a.ravel(order='C')   

array([10, 20, 30, 40, 50, 60])

In [70]:
a.ravel(order='F')   

array([10, 40, 20, 50, 30, 60])

In [71]:
a.flatten()

array([10, 20, 30, 40, 50, 60])

In [74]:
a=np.array([[1,2,3]]) # 2차원 형태로 넣어줌

In [78]:
a_=np.array([1,2,3]) # 1차원 형태로 넣어줌

> ### `차이점`

In [80]:
a_[0]

1

In [81]:
a[0][0]

1

----

In [83]:
a.ndim

2

In [84]:
a.shape

(1, 3)

2차원에서 1차원으로 줄이자

In [85]:
b=a.squeeze()

In [86]:
b

array([1, 2, 3])

In [87]:
b.ndim

1

In [88]:
b.shape

(3,)

In [89]:
a=np.array([[[1,2]],[[3,4]],[[5,6]]])

In [90]:
a

array([[[1, 2]],

       [[3, 4]],

       [[5, 6]]])

In [91]:
a.shape

(3, 1, 2)

In [92]:
a.ndim

3

In [93]:
b=a.squeeze()

In [94]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [95]:
b.shape

(3, 2)

In [107]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [98]:
a.shape

(3,)

In [100]:
a_=a[:,np.newaxis]
b_=b[:,np.newaxis]
# 차원 하나 추가

In [101]:
a_.shape

(3, 1)

In [102]:
np.concatenate((a_,b_),axis=0)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [103]:
np.concatenate((a_,b_),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [111]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [112]:
np.vstack((a,b)).transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [116]:
np.hstack((a,b)).reshape((2,3)).transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

> shallow copy

> deep copy

In [118]:
a=np.array([10,20,30])

In [119]:
b=a

In [120]:
b

array([10, 20, 30])

In [122]:
b[0]=909

In [123]:
b

array([909,  20,  30])

In [124]:
a

array([909,  20,  30])

In [126]:
b is a

True

> 즉 같은 메모리에 이름만 다르게 저장된 것

In [127]:
a=np.array([1,2,3,4])

In [128]:
b=a.view()

In [129]:
b

array([1, 2, 3, 4])

In [131]:
b is a

False

In [132]:
b[0]=123123

In [133]:
a

array([123123,      2,      3,      4])

In [134]:
b

array([123123,      2,      3,      4])

> `shallow copy`를 했음에도 같이 업데이트 되어버림

In [137]:
b.shape=(2,2)

In [138]:
b

array([[123123,      2],
       [     3,      4]])

In [139]:
b[0][1]=111

In [140]:
b

array([[123123,    111],
       [     3,      4]])

In [141]:
a

array([123123,    111,      3,      4])

> 즉 shallow copy란 메모리 상에 data는 같이 공유하지만 array의 shape은 공유 X

그렇다면 deep copy?

In [142]:
a=np.array([10,20,30,40])

In [143]:
b=a.copy()

In [144]:
b[0]=8999

In [145]:
a

array([10, 20, 30, 40])

In [146]:
b

array([8999,   20,   30,   40])

In [147]:
a is b

False

In [148]:
b.base is a

False

> `즉 b만의 온전한 데이터를 만들 수 있음`

----

In [164]:
a=np.array([55,0,12,3,4])

In [165]:
# a의 모든 값이 참?
# 여기선 0, 즉 FALSE값이 들어있기 때문에 FALSE로 나올 것
a.all()

False

In [166]:
# 하나라도 참이 들어있는지?
a.any()

True

In [168]:
# 0이 아닌 값들의 index를 알 수 있음
a.nonzero()

(array([0, 2, 3, 4], dtype=int64),)

In [171]:
# 0보다 큰 거 어디? index로 알려줄 것
np.where(a>0)

(array([0, 2, 3, 4], dtype=int64),)

In [173]:
np.where(a==0)

(array([1], dtype=int64),)

In [174]:
np.where(a!=0)

(array([0, 2, 3, 4], dtype=int64),)

data filtering에 유용하게 사용될 것